### PR TITLE
Add mention for all CLIs in README

### LINKED ISSUE #46: Fix README to show other binaries as well
As we add more binaries, we should make it easier to discover them from the README, but without sacrificing the spotlight provided to the `ipinfo` binary specifically. Right now there's little to no indication that anything besides `ipinfo` exists, unless you look at the releases yourself or look at the code.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Closes #46

### CODE REVIEW

**Comment by UmanShahzad** [comment]
@coderholic do you have any suggestions for a better presentation? See this link for a rich view of what's proposed: https://github.com/ipinfo/cli/blob/fda89d30cf15eac6cc18cb76f677adabe2c1ece1/README.md

**Comment by coderholic** [comment]
I think we want to drive most downloads/installs of the main `ipinfo` cli, so I don't think we should give so much attention to the others. Maybe a section on "Additional clis" or something, that says "These subcommands are also available as standalone binaries... you can install / setup like x..."?

**Comment by UmanShahzad** [comment]
Yeah I agree with that, especially considering all other CLI functionality is embedded in the `ipinfo` one. I'll change this up to match that model a bit (maybe a separate section in `Installation` for mentioning that all these other CLIs exist and they can be downloaded the same way, just replace name, etc).

**Comment by UmanShahzad** [comment]
Added "additional CLIs" section at https://github.com/ipinfo/cli#additional-clis

**Pull request merged**
