### PR TITLE
cli prints error if free user filters out paid fields

### PR DESCRIPTION
**Pull request by Taimoor-12**
The CLI prints an error message when a user with a token attempts to access paid data for which they do not have permission.

Before:
Screenshot from 2024-03-01 12-44-00

After:
Screenshot from 2024-03-01 12-44-29

If the token has access to every premium data but no carrier data is associated with the IP:
Screenshot from 2024-03-01 12-45-16

About 6 types of paid data could be sent to the user depending on their token. These paid data include ASN, Company, Carrier, Privacy, Abuse and Domains. 

We have multiple price plans for the user behind the token:
- Free plan (no paid data is sent in the API response).
- Basic plan (user only receives ASN data).
- Standard plan (user receives ASN and Privacy data).
- Business plan (user receives all types of paid data, except carrier data, which depends on the specific IP address).

This information is taken from the [sample API responses for different price plans](https://ipinfo.io/pricing)

### CODE REVIEW

**Comment by UmanShahzad** [comment]
@Taimoor-12 carrier info only gets printed if the IP in question has carrier data associated with it. Not all IPs do.

Also can't update `vendor/` that's meant to be auto-generated code via `go mod vendor`.

The error message is fine but needs to be collated.

**Comment by Taimoor-12** [comment]
@UmanShahzad updated the examples in description after incorporating the changes.

**Review by UmanShahzad — COMMENTED** [review]
Looked at the code now...

We need to find a better way to handle this, not like this. This is a mess. Error handling shouldn't be sprawling and change how the fundamental logic runs so deeply. It makes it x10 harder to understand what is even happening now.

We had discussions on the method to use here.

**Comment by Taimoor-12** [comment]
Attempted separating error handling with the core logic of outputting data. Before even attempting to output, we now determine user's access rights and associated errors by inspecting the `Core` struct and pass that information to the output function.

**Pull request closed without merging**
