### PR TITLE
country details in pretty view

### PR DESCRIPTION
**Pull request by rm-Umar**
solves #123

### CODE REVIEW

**Review by UmanShahzad — COMMENTED** [review]
Wrong UI! This needs to be included in the same `Core` section, doesn't need a whole new section.

We can add something like this:

```
Core
- IP           1.1.1.1
- Anycast      true
- Hostname     one.one.one.one
- City         Los Angeles
- Region       California
- Country      United States (US)
- Flag         🇺🇸
- Currency     USD ($)
- Location     34.0522,-118.2437
- Organization AS13335 Cloudflare, Inc.
- Postal       90076
- Timezone     America/Los_Angeles
```

**Review by UmanShahzad — APPROVED** [review]

**Comment by yermulnik** [comment]
It seems like this feature produces strange artifact in my terminal (I'm still looking into how to fix this from terminal app end). Is there a way to turn this feature off by default or via command line arg? Thanks.
image

**Comment by yermulnik** [comment]
Tested with different term apps and this either shows oddly or doesn't show up at all based on chosen font. Some fonts do stretch this "emoji" so letters don't overlap, some don't. I really would appreciate this to be togglable. Thank you.

**Comment by yermulnik** [comment]
I filed https://github.com/ipinfo/cli/issues/144 to track this.

**Pull request merged**
